Feature branch
azeezumoru/abdul-portfolio pull request #1
Opened 2022-10-27 20:00 UTC by azeezumoru

This project is about the toolbar (or header).
This project is about the headline section (right after the header)

2022-10-27 21:37 UTC, vickymarz requested changes
Hi @azeezumoru, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅ 
- The PR title and description are professional and descriptive ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 21:37 UTC, vickymarz commented on index.html
> +                <img src="./images/twitter.png" alt="" class="social">
- [ ] I think it will be better if you reduce the spacing between your social icons to match the Figma design you chose  👍🏽

Your Design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/198401512-c8da80a4-adef-4138-b8a6-77aa9967010a.png)

Figma Design

![image](https://user-images.githubusercontent.com/63473584/198401446-4bed74d1-6c24-46c7-9edb-bbeac44043ab.png)

2022-10-27 21:37 UTC, vickymarz commented on index.html
> +          <h1 class="main-title">Hey There. I am Umoru</h1>
- [ ] I think it will be better if you increase the `font-weight` of your headline title to match the Figma design template you chose so that your UI will look great 😄 

Figma Design 👇🏽 

![image](https://user-images.githubusercontent.com/63473584/198402437-6b2decf2-4733-4cb1-bb5a-99d946147054.png)

Your Design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/198402530-bd7e5f11-3b0e-4085-83f2-608d11d4de38.png)

2022-10-27 21:37 UTC, vickymarz commented on index.html
> +            <i class="material-icons">menu</i>
- [ ] I will recommend you center the content of your toolbar so that your UI can be much nicer 👍🏽 

 
![image](https://user-images.githubusercontent.com/63473584/198402926-748139da-dc01-42e4-80ee-b46676425374.png)

2022-10-28 05:53 UTC, sajid-munawar approved these changes
### Hi @azeezumoru , 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Followed Github flow :heavy_check_mark:
- Professional README file. :heavy_check_mark:
- PR has a good title and description :heavy_check_mark:
 
 ## [Optional] suggestions:
 * [ ]  Please check my inline comments.

> _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
> 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @sajid-munawar in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 08:07 UTC, merged